name = "assets-auth"                                                                                                            
main = "src/index.js"                                                                                                           
compatibility_date = "2026-04-03"                                                                                               
                                                                                                                                  
# 可选：如果你有自定义 workers.dev                                                                                              
# workers_dev = true                                                                                                            
                                                                                                                                  
[[r2_buckets]]                                                                                                                  
binding = "pictures_lib"                                                                                                       
bucket_name = "pictures-lib"  

[vars]
ALLOWED_ORIGINS = "https://timberfirear.cc,https://www.timberfirear.cc"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1