name = "assets-auth-preview"
main = "src/index.js"
compatibility_date = "2026-04-03"
workers_dev = true

[[r2_buckets]]
binding = "pictures_lib"
bucket_name = "pictures-lib"

[vars]
ALLOWED_ORIGINS = "https://1dsc.fyi"
SIGNED_URL_TTL = "31536000"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
